docs: add utility functions to README
nuxt-contrib/h2 pull request #16
Opened 2020-12-14 15:53 UTC by farnabaz

2020-12-14 16:18 UTC, Atinux commented
Thanks @farnabaz 

While we are at this, I would like to suggest to rename `useBody` to `useBodyRaw` and having the parsing with `destr` by default for `useBody`.

Do you agree @pi0 ?

2020-12-14 16:19 UTC, Atinux commented on README.md
> +app.use('/api', (req) => ({ queryParams: useQuery(req) }))
```suggestion
app.use('/api', (req) => ({ query: useQuery(req) }))
```

I will also show a quick url example:

/api?hello=world&array[]=one&array=two will return `{ hello: 'world', array: ['one', 'two] }`

2020-12-14 16:30 UTC, pi0 requested changes
This is partial documentation which might be misleading. We shall include docs for all utils (like including sendError, promisify, etc)  or not. As suggested in other PR we may use JSDocs to maintain update docs with utils

2020-12-14 16:46 UTC, Atinux commented
I see, fully agree with JSDocs for automated docs 🔥

2020-12-14 16:47 UTC, pi0 commented
> While we are at this, I would like to suggest to rename useBody to useBodyRaw and having the parsing with destr by default for useBody.

Makes sense

2020-12-15 09:40 UTC, farnabaz commented
I've started using jsdoc and added comments to some functions. It is not completed yet.  
The result is available here: http://h2-docs.surge.sh/

2020-12-15 10:09 UTC, pi0 commented
@farnabaz Kindly please stop doing actions without consulting repo maintainer via issues!! This time I revert unnecessary changes but next time will simply close PR. Thanks.

2020-12-15 10:18 UTC, merged